<?php
/**
 * Implements hook_filter_info().
 */
function druit_filter_info() {
  $filters['filter_druitter'] = array(
    'title' => t('Twitter like filter'),
    'description' => t('Converts #hashtags and @usernames in internal links.'),
    'process callback' => 'druit_filter_druitter',
  );

  return $filters;
}

/**
 * Implements the processing.
 */
function druit_filter_druitter($text, $filter, $format) {
  $patterns = array(
    '/@([a-zA-Z0-9]+)/', // User links
    '/#([a-zA-Z0-9]+)/', // Hashtag links
  );
  $replacements = array(
    '<a href="/${0}">${0}</a>',
    '<a href="/s/${1}">${0}</a>',
  );

  $text = preg_replace($patterns, $replacements, $text);
  return $text;
}

/**
 * Implements hook_field_formatter_info().
 */
function druit_field_formatter_info() {
  return array(
    'druit' => array(
      'label' => t('Druit'),
      'field types' => array('text'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function druit_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  if ($display['type'] == 'druit') {
    foreach ($items as $delta => $item) {
      $output = check_markup($item['value'], 'druitter');
      $element[$delta] = array('#markup' => $output);
    }
  }

  return $element;
}
